import { z } from "zod";
import { Address, internal, toNano, beginCell } from "@ton/core";

import { defineAction, toFriendlyAddress, sendTransaction } from "@ton-agent-kit/core";
import { saveReputationConfig } from "../reputation-config";

export const deployReputationContractAction = defineAction({
  name: "deploy_reputation_contract",
  description:
    "Deploy the on-chain Reputation smart contract (Tact) to TON. Once deployed, register_agent and get_agent_reputation will use it automatically for verifiable, immutable reputation scores.",
  schema: z.object({
    fee: z
      .string()
      .optional()
      .describe("Fee per write operation in TON. Defaults to '0.01'."),
  }),
  handler: async (agent, params) => {
    try {
      // Dynamic import of compiled Tact contract
      // This file is generated by: bun run contracts/deploy-reputation.ts
      let Reputation: any;
      let storeDeploy: any;
      try {
        const mod = await import("../contracts/Reputation_Reputation");
        Reputation = mod.Reputation;
        storeDeploy = mod.storeDeploy;
      } catch {
        return {
          deployed: false,
          message:
            "Compiled contract not found. Run 'bun run contracts/deploy-reputation.ts' first to compile the Tact contract, then copy output to packages/plugin-identity/src/contracts/.",
        };
      }

      const ownerAddress = agent.wallet.address;
      const reputation = await Reputation.fromInit(ownerAddress);

      const deployBody = beginCell()
        .store(storeDeploy({ $$type: "Deploy", queryId: BigInt(0) }))
        .endCell();

      await sendTransaction(agent, [
        internal({
          to: reputation.address,
          value: toNano("0.05"),
          bounce: false,
          init: reputation.init!,
          body: deployBody,
        }),
      ]);

      const contractAddr = reputation.address.toRawString();

      // Save config so other actions auto-detect the contract
      saveReputationConfig({
        contractAddress: contractAddr,
        network: agent.network,
        deployedAt: new Date().toISOString(),
      });

      return {
        deployed: true,
        contractAddress: contractAddr,
        friendlyContract: toFriendlyAddress(reputation.address, agent.network),
        network: agent.network,
        fee: params.fee || "0.01",
        message: `Reputation contract deployed at ${toFriendlyAddress(reputation.address, agent.network)}. Agents can now register on-chain.`,
      };
    } catch (err: any) {
      return {
        deployed: false,
        error: err.message,
        message: `Failed to deploy reputation contract: ${err.message}`,
      };
    }
  },
});
